description =  """Base directory containing all files, index.ts is the entry point and runs git apply, triggers prompt, etc
  Prompt.ts contains methods pertaining to prompting via openai api
  overview contains methods pertaining to generating directory description"""
